# Docker Compose file for R2D3 Robot Development Environment

services:
  # ROS2 Humble R2D3 Robot (Default/Recommended)
  r2d3-humble:
    build:
      context: docker
      dockerfile: Dockerfile.humble
      args:
        USERNAME: ros
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    image: ros2-humble-r2d3:latest
    container_name: r2d3-humble
    hostname: r2d3-humble
    restart: unless-stopped
    privileged: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-1}
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - ROS_DISTRO=humble
      - WORKSPACE_DIR=/home/ros/ros2_ws
    volumes:
      # X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Shared memory
      - /dev/shm:/dev/shm:rw
      # PulseAudio
      - /run/user/${USER_UID:-1000}/pulse:/run/user/1000/pulse:rw
      # Project source code
      - ./scripts:/home/ros/scripts:ro
      # Persistent workspace
      - r2d3_humble_workspace:/home/ros/ros2_ws
      # Persistent home directory
      - r2d3_humble_home:/home/ros/persistent_home
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    security_opt:
      - apparmor=unconfined
    working_dir: /home/ros
    command: >
      bash -c "
        # Setup persistent home directory
        if [ ! -f /home/ros/persistent_home/.setup_complete ]; then
          echo 'Setting up persistent home directory...'
          cp -r /home/ros/.bashrc /home/ros/.profile /home/ros/persistent_home/ 2>/dev/null || true
          ln -sf /home/ros/persistent_home/.bashrc /home/ros/.bashrc 2>/dev/null || true
          ln -sf /home/ros/persistent_home/.profile /home/ros/.profile 2>/dev/null || true
        fi
        
        # Run setup scripts if not already done
        if [ ! -f /home/ros/ros2_ws/.setup_complete ]; then
          echo 'Running R2D3 setup...'
          sudo mkdir -p /run/user/1000/pulse
          sudo chown -R ros:ros /run/user/1000
          sudo chmod 700 /run/user/1000/pulse
          /home/ros/scripts/setup_devcontainer.sh
          /home/ros/scripts/setup_r2d3.sh
          touch /home/ros/ros2_ws/.setup_complete
          touch /home/ros/persistent_home/.setup_complete
        fi
        
        # Source ROS environment
        source /opt/ros/humble/setup.bash
        if [ -f /home/ros/ros2_ws/install/setup.bash ]; then
          source /home/ros/ros2_ws/install/setup.bash
        fi
        
        echo 'R2D3 Humble environment ready!'
        echo 'Run: ~/scripts/setup_r2d3.sh to clone and install R2D3 packages'
        echo 'Available after setup: r2d3_ws, r2d3_build, r2d3_camera, r2d3_demo'
        exec bash
      "
    profiles:
      - humble
      - default

  # ROS2 Foxy R2D3 Robot (Original)
  r2d3-foxy:
    build:
      context: docker
      dockerfile: Dockerfile.foxy
      args:
        USERNAME: ros
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    image: ros2-foxy-r2d3:latest
    container_name: r2d3-foxy
    hostname: r2d3-foxy
    restart: unless-stopped
    privileged: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-1}
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - ROS_DISTRO=foxy
      - WORKSPACE_DIR=/home/ros/ros2_ws
    volumes:
      # X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Shared memory
      - /dev/shm:/dev/shm:rw
      # PulseAudio
      - /run/user/${USER_UID:-1000}/pulse:/run/user/1000/pulse:rw
      # Project source code
      - ./scripts:/home/ros/scripts:ro
      # Persistent workspace
      - r2d3_foxy_workspace:/home/ros/ros2_ws
      # Persistent home directory
      - r2d3_foxy_home:/home/ros/persistent_home
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    security_opt:
      - apparmor=unconfined
    working_dir: /home/ros
    command: >
      bash -c "
        # Setup basic directories
        sudo mkdir -p /run/user/1000/pulse 2>/dev/null || true
        sudo chown -R ros:ros /run/user/1000 2>/dev/null || true
        sudo chmod 700 /run/user/1000/pulse 2>/dev/null || true
        
        # Source ROS environment
        source /opt/ros/foxy/setup.bash
        
        echo 'R2D3 Foxy environment ready!'
        echo 'Run: ~/scripts/setup_r2d3.sh to clone and install R2D3 packages'
        echo 'Available after setup: r2d3_ws, r2d3_build, r2d3_camera, r2d3_demo'
        
        # Keep container running
        tail -f /dev/null
      "
    profiles:
      - foxy

  # ROS2 Jazzy R2D3 Robot (Latest)
  r2d3-jazzy:
    build:
      context: docker
      dockerfile: Dockerfile.jazzy
      args:
        USERNAME: ros
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    image: ros2-jazzy-r2d3:latest
    container_name: r2d3-jazzy
    hostname: r2d3-jazzy
    restart: unless-stopped
    privileged: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-1}
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - ROS_DISTRO=jazzy
      - WORKSPACE_DIR=/home/ros/ros2_ws
    volumes:
      # X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Shared memory
      - /dev/shm:/dev/shm:rw
      # PulseAudio
      - /run/user/${USER_UID:-1000}/pulse:/run/user/1000/pulse:rw
      # Project source code
      - ./scripts:/home/ros/scripts:ro
      # Persistent workspace
      - r2d3_jazzy_workspace:/home/ros/ros2_ws
      # Persistent home directory
      - r2d3_jazzy_home:/home/ros/persistent_home
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    security_opt:
      - apparmor=unconfined
    working_dir: /home/ros
    command: >
      bash -c "
        # Setup persistent home directory
        if [ ! -f /home/ros/persistent_home/.setup_complete ]; then
          echo 'Setting up persistent home directory...'
          cp -r /home/ros/.bashrc /home/ros/.profile /home/ros/persistent_home/ 2>/dev/null || true
          ln -sf /home/ros/persistent_home/.bashrc /home/ros/.bashrc 2>/dev/null || true
          ln -sf /home/ros/persistent_home/.profile /home/ros/.profile 2>/dev/null || true
        fi
        
        # Run setup scripts if not already done
        if [ ! -f /home/ros/ros2_ws/.setup_complete ]; then
          echo 'Running R2D3 setup...'
          sudo mkdir -p /run/user/1000/pulse
          sudo chown -R ros:ros /run/user/1000
          sudo chmod 700 /run/user/1000/pulse
          /home/ros/scripts/setup_devcontainer.sh
          /home/ros/scripts/setup_r2d3.sh
          touch /home/ros/ros2_ws/.setup_complete
          touch /home/ros/persistent_home/.setup_complete
        fi
        
        # Source ROS environment
        source /opt/ros/jazzy/setup.bash
        if [ -f /home/ros/ros2_ws/install/setup.bash ]; then
          source /home/ros/ros2_ws/install/setup.bash
        fi
        
        echo 'R2D3 Jazzy environment ready!'
        echo 'Run: ~/scripts/setup_r2d3.sh to clone and install R2D3 packages'
        echo 'Available after setup: r2d3_ws, r2d3_build, r2d3_camera, r2d3_demo'
        exec bash
      "
    profiles:
      - jazzy

volumes:
  # Separate persistent volumes for each distribution
  r2d3_humble_workspace:
    driver: local
  r2d3_humble_home:
    driver: local
  r2d3_foxy_workspace:
    driver: local
  r2d3_foxy_home:
    driver: local
  r2d3_jazzy_workspace:
    driver: local
  r2d3_jazzy_home:
    driver: local

networks:
  default:
    name: r2d3_network
